#!/usr/bin/env python3
"""Regenerates world_map.h and vecfont.h for WorldRing and CyberCycle.

    cd WorldRing/tools && python3 generate.py

world.py holds the coarse continent outlines, vecfont.py the stroke font.
Edit those, re-run this, and the sketch picks the new tables up on compile.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import world, vecfont

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
# CyberCycle carries its own copy of both tables: the Arduino IDE only
# compiles files sitting in the sketch folder, so they cannot be shared.
OUTS = [os.path.join(ROOT, "WorldRing"), os.path.join(ROOT, "CyberCycle")]


def wrap(vals, per_line, fmt="%d"):
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append("  " + ", ".join(fmt % v for v in vals[i:i + per_line]) + ",")
    return "\n".join(lines)


def gen_map():
    lon_n, lat_n = world.LON_N, world.LAT_N
    assert lon_n == 256, "the sketch relies on LON_N == 256 for free uint8 wrap-around"
    mask = world.build_mask(lon_n, lat_n)
    packed = []
    for row in mask:
        for byte in range(lon_n // 8):
            v = 0
            for b in range(8):
                if row[byte * 8 + b]:
                    v |= 1 << (7 - b)
            packed.append(v)
    body = wrap(packed, 16, "0x%02X")
    text = (f"""// Generated by tools/generate.py - do not edit by hand.
// Coarse equirectangular land mask, 1 bit per cell, row 0 = north pole.
#pragma once
#include <Arduino.h>

#define MAP_LON {lon_n}
#define MAP_LAT {lat_n}
#define MAP_ROW_BYTES ({lon_n} / 8)

static const uint8_t WORLD_MAP[] PROGMEM = {{
{body}
}};

// lat 0..MAP_LAT-1 (north to south), lon 0..255 (wraps on its own as uint8)
static inline bool landAt(uint8_t lat, uint8_t lon) {{
  uint8_t b = pgm_read_byte(&WORLD_MAP[lat * MAP_ROW_BYTES + (lon >> 3)]);
  return (b >> (7 - (lon & 7))) & 1;
}}
""")
    for d in OUTS:
        open(os.path.join(d, "world_map.h"), "w").write(text)
    print("world_map.h  %d bytes of table -> %d sketches" % (len(packed), len(OUTS)))


def gen_font():
    strokes = []
    index = [0xFFFF] * 256
    for ch in vecfont.ORDER:
        index[ord(ch)] = len(strokes)
        for pl in vecfont.G[ch]:
            for (x, y) in pl:
                strokes += [x, y]
            strokes.append(-128)          # end of polyline
        strokes.append(-127)              # end of glyph
    # lowercase maps onto uppercase
    for c in range(ord('a'), ord('z') + 1):
        index[c] = index[c - 32]
    body = wrap(strokes, 20)
    idx = wrap(index, 12)
    text = (f"""// Generated by tools/generate.py - do not edit by hand.
// Stroke font on a 5x7 cell (x 0..4, y 0..6, y=0 is the cap line).
// Vector outlines so glyphs can be rotated to follow the ring.
#pragma once
#include <Arduino.h>

#define VF_W 5          // cell width  in font units
#define VF_H 7          // cell height in font units
#define VF_END_POLY  (-128)
#define VF_END_GLYPH (-127)

static const int8_t VF_STROKES[] PROGMEM = {{
{body}
}};

// byte value -> offset into VF_STROKES, 0xFFFF when the glyph is missing
static const uint16_t VF_INDEX[256] PROGMEM = {{
{idx}
}};
""")
    for d in OUTS:
        open(os.path.join(d, "vecfont.h"), "w").write(text)
    print("vecfont.h    %d stroke bytes -> %d sketches" % (len(strokes), len(OUTS)))


gen_map()
gen_font()
